# Generated by Django 4.1.1 on 2023-01-20 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeFac', models.CharField(max_length=10, unique=True)),
                ('denomination_extact', models.TextField()),
            ],
            options={
                'ordering': ['codeFac'],
            },
        ),
        migrations.CreateModel(
            name='promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codePromotion', models.CharField(max_length=15, unique=True)),
                ('denomination_exact_Promo', models.TextField()),
                ('faclte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vote.faculte')),
            ],
            options={
                'ordering': ['codePromotion'],
            },
        ),
    ]
