# Generated by Django 4.1.1 on 2023-01-20 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={'ordering': ['nom']},
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='promotion',
        ),
    ]
